// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgg3BhCkS7YX7Itt5iS5w7-4t9NHvGpqM',
    appId: '1:612864539576:android:36d9aedb8a10d077322d4d',
    messagingSenderId: '612864539576',
    projectId: 'smarthome-ssi-test',
    databaseURL: 'https://smarthome-ssi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-ssi-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCRJYUHQ7fhHtxF-uqrDrK36Kq3y2ku24',
    appId: '1:612864539576:ios:3254635c0e3f49da322d4d',
    messagingSenderId: '612864539576',
    projectId: 'smarthome-ssi-test',
    databaseURL: 'https://smarthome-ssi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthome-ssi-test.firebasestorage.app',
    iosBundleId: 'com.example.roomAutomation',
  );
}
